[tool.poetry]
name = "pokehub-manager"
version = "0.1.0"
description = "A discord Bot for managing Citra Pokéhub Server. https://discord.gg/n5zdSC6Ftb"
authors = ["Sayan Barma: sayanbarma2004@gmail.com"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
flask = "^1.1.2"
youtube-dl = "^2021.2.10"
PyNaCl = "^1.4.0"
googletrans = "3.1.0a0"
better-profanity = "^0.7.0"
google = "^3.0.0"
pydictionary = "^2.0.1"
urbandictionary = "^1.1"
bs4 = "^0.0.1"
replit = "^2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
