[tool.poetry]
name = "pokehub-manager"
version = "0.1.0"
description = "A discord Bot for managing Citra Pokéhub Server. https://discord.gg/n5zdSC6Ftb"
authors = ["Sayan Barma: sayanbarma2004@gmail.com"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
flask = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
